### ISSUE TITLE
改进 - 首页改进

### ISSUE THREAD

**Issue by liujunlj** [Yunins/gaokaoapp#6]
1. 火箭上叠加的文字，建议去掉
2. 将这行文字移到火箭上方，一行，居中

![5091553234877_ pic](https://user-images.githubusercontent.com/11909338/54803854-275cf480-4cac-11e9-88d7-29aeeb0ebc5e.jpg)

**Comment by tgi-no-one** [comment]
已修改。

![image](https://user-images.githubusercontent.com/48739934/54865570-52297480-4da2-11e9-9c56-fd170f0fc7e4.png)
