### ISSUE TITLE
改进 - 查看具体推荐院校界面

### ISSUE THREAD

**Issue by liujunlj** [Yunins/gaokaoapp#8]
1. 院校简介信息那，是不是应该院校隶属和院校类型，在上面一行，教育部，工科、985这些在下面一行？总感觉现在是反着的
2. 查看具体院校时，下面的信息栏排序为：往年录取情况、今年招生计划、开设专业列表、招生联系方式
3. 查看具体院校时，历年位次的表上方，增加一行”当前考生的省内排名为：xxxx“

**Comment by tgi-no-one** [comment]
1和3还没有调整，新一版原型中调整。2原型输出过了，小程序在调整中...
